[build]
  publish = "."
  command = ""

# Redirects for static assets (must come before SPA fallback)
[[redirects]]
  from = "/styles/*"
  to = "/styles/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

# PRIORITY 1: Handle .html to clean URL redirects FIRST (before domain redirects)
# This prevents redirect chains
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/privacy.html"
  to = "/privacy"
  status = 301
  force = true

[[redirects]]
  from = "/terms.html"
  to = "/terms"
  status = 301
  force = true

[[redirects]]
  from = "/partnerships.html"
  to = "/partnerships"
  status = 301
  force = true

[[redirects]]
  from = "/curriculum.html"
  to = "/curriculum"
  status = 301
  force = true

[[redirects]]
  from = "/scientific_validation.html"
  to = "/scientific_validation"
  status = 301
  force = true

[[redirects]]
  from = "/consciousness_bands.html"
  to = "/consciousness_bands"
  status = 301
  force = true

[[redirects]]
  from = "/consciousness_accelerator.html"
  to = "/consciousness_accelerator"
  status = 301
  force = true

[[redirects]]
  from = "/app_screens.html"
  to = "/app_screens"
  status = 301
  force = true

[[redirects]]
  from = "/project_proposal.html"
  to = "/project_proposal"
  status = 301
  force = true

[[redirects]]
  from = "/advanced_concepts.html"
  to = "/advanced_concepts"
  status = 301
  force = true

[[redirects]]
  from = "/academic_alignment.html"
  to = "/academic_alignment"
  status = 301
  force = true

[[redirects]]
  from = "/app_features.html"
  to = "/app_features"
  status = 301
  force = true

[[redirects]]
  from = "/business_model.html"
  to = "/business_model"
  status = 301
  force = true

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/implementation_plan.html"
  to = "/implementation_plan"
  status = 301
  force = true

[[redirects]]
  from = "/quantum_parameters.html"
  to = "/quantum_parameters"
  status = 301
  force = true

[[redirects]]
  from = "/understanding-quantum-self.html"
  to = "/understanding-quantum-self"
  status = 301
  force = true

[[redirects]]
  from = "/technical_implementation.html"
  to = "/technical_implementation"
  status = 301
  force = true

[[redirects]]
  from = "/quantum-mind.html"
  to = "/quantum-mind"
  status = 301
  force = true

[[redirects]]
  from = "/future-self-integration.html"
  to = "/future-self-integration"
  status = 301
  force = true

[[redirects]]
  from = "/entanglement-log.html"
  to = "/entanglement-log"
  status = 301
  force = true

[[redirects]]
  from = "/entangled-realities.html"
  to = "/entangled-realities"
  status = 301
  force = true

[[redirects]]
  from = "/advanced_progression.html"
  to = "/advanced_progression"
  status = 301
  force = true

[[redirects]]
  from = "/search.html"
  to = "/search"
  status = 301
  force = true

[[redirects]]
  from = "/progress.html"
  to = "/progress"
  status = 301
  force = true

# PRIORITY 2: Domain redirects (HTTP → HTTPS, non-www → www)
# These handle domain-level redirects after .html redirects are processed
[[redirects]]
  from = "http://quannex.earth/*"
  to = "https://www.quannex.earth/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.quannex.earth/*"
  to = "https://www.quannex.earth/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://quannex.earth/*"
  to = "https://www.quannex.earth/:splat"
  status = 301
  force = true

# PRIORITY 3: Fix 404 errors - redirect misnamed files to correct locations
[[redirects]]
  from = "/academic.html"
  to = "/academic_alignment"
  status = 301

[[redirects]]
  from = "/academic"
  to = "/academic_alignment"
  status = 301

[[redirects]]
  from = "/advanced.html"
  to = "/advanced_concepts"
  status = 301

[[redirects]]
  from = "/advanced"
  to = "/advanced_concepts"
  status = 301

[[redirects]]
  from = "/success.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/success"
  to = "/"
  status = 301

[[redirects]]
  from = "/resources.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/resources"
  to = "/"
  status = 301

# Chat widget fix - redirect DivineChatWidget to QuannexChatWidget
[[redirects]]
  from = "/components/common/DivineChatWidget.html"
  to = "/QuannexChatWidget.html"
  status = 301

[[redirects]]
  from = "/DivineChatWidget.html"
  to = "/QuannexChatWidget.html"
  status = 301

# Delivery folder redirects
[[redirects]]
  from = "/delivery/empty.html"
  to = "/public/delivery/empty.html"
  status = 200

[[redirects]]
  from = "/delivery/"
  to = "/"
  status = 301

# ConsentManager related files - redirect to main site
[[redirects]]
  from = "/delivery/cmp.php"
  to = "/"
  status = 301

[[redirects]]
  from = "/cmp_final"
  to = "/"
  status = 301

[[redirects]]
  from = "/cmp.php"
  to = "/"
  status = 301

# Block component files from direct access
[[redirects]]
  from = "/component-*.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/components/*"
  to = "/"
  status = 301

# PRIORITY 4: Clean URL redirects - serve HTML files at clean URLs (200 rewrites)
# These happen AFTER all 301 redirects are processed
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/partnerships"
  to = "/partnerships.html"
  status = 200

[[redirects]]
  from = "/curriculum"
  to = "/curriculum.html"
  status = 200

[[redirects]]
  from = "/scientific_validation"
  to = "/scientific_validation.html"
  status = 200

[[redirects]]
  from = "/consciousness_bands"
  to = "/consciousness_bands.html"
  status = 200

[[redirects]]
  from = "/consciousness_accelerator"
  to = "/consciousness_accelerator.html"
  status = 200

[[redirects]]
  from = "/app_screens"
  to = "/app_screens.html"
  status = 200

[[redirects]]
  from = "/project_proposal"
  to = "/project_proposal.html"
  status = 200

[[redirects]]
  from = "/advanced_concepts"
  to = "/advanced_concepts.html"
  status = 200

[[redirects]]
  from = "/academic_alignment"
  to = "/academic_alignment.html"
  status = 200

[[redirects]]
  from = "/app_features"
  to = "/app_features.html"
  status = 200

[[redirects]]
  from = "/business_model"
  to = "/business_model.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/implementation_plan"
  to = "/implementation_plan.html"
  status = 200

[[redirects]]
  from = "/quantum_parameters"
  to = "/quantum_parameters.html"
  status = 200

[[redirects]]
  from = "/understanding-quantum-self"
  to = "/understanding-quantum-self.html"
  status = 200

[[redirects]]
  from = "/technical_implementation"
  to = "/technical_implementation.html"
  status = 200

[[redirects]]
  from = "/quantum-mind"
  to = "/quantum-mind.html"
  status = 200

[[redirects]]
  from = "/future-self-integration"
  to = "/future-self-integration.html"
  status = 200

[[redirects]]
  from = "/entanglement-log"
  to = "/entanglement-log.html"
  status = 200

[[redirects]]
  from = "/entangled-realities"
  to = "/entangled-realities.html"
  status = 200

[[redirects]]
  from = "/advanced_progression"
  to = "/advanced_progression.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/progress"
  to = "/progress.html"
  status = 200

# CSS legacy redirects
[[redirects]]
  from = "/styles.css"
  to = "/styles/styles.css"
  status = 200

[[redirects]]
  from = "/dropdown.css"
  to = "/styles/dropdown.css"
  status = 200

# Blog routes - ensure they work with Next.js
[[redirects]]
  from = "/entanglement-log/*"
  to = "/entanglement-log/:splat"
  status = 200

# SPA fallback for all other routes (but not blog routes or any .html file)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = {match = "^(?!entanglement-log)(?!.*\\.html$).*"}}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self' https://cdn.consentmanager.net https://a.delivery.consentmanager.net; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.consentmanager.net https://a.delivery.consentmanager.net https://www.googletagmanager.com https://identity.netlify.com; style-src 'self' 'unsafe-inline' https://cdn.consentmanager.net https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https: https://i.imgur.com https://imgur.com; font-src 'self' data: https: https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://a.delivery.consentmanager.net https://region1.analytics.google.com https://www.google-analytics.com; frame-src 'self' https://cdn.consentmanager.net; object-src 'none'; base-uri 'self'; form-action 'self';"
    Cache-Control = "public, max-age=0, must-revalidate"

# Prevent indexing of .html files to avoid duplicate content
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Exception: Allow indexing of index.html (but it redirects anyway)
[[headers]]
  for = "/index.html"
  [headers.values]
    X-Robots-Tag = "noindex, follow"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Prevent indexing of component files
[[headers]]
  for = "/component-*.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/components/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Forms configuration
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Netlify Functions (if needed in the future)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "."
  autoLaunch = true

[functions."quannex_intelligence"]
  included_files = ["netlify/functions/knowledge.json"] 