[build]
  publish = "."
  command = ""

# Redirects for static assets (must come before SPA fallback)
[[redirects]]
  from = "/styles/*"
  to = "/styles/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = """
      default-src 'self' https://cdn.consentmanager.net https://a.delivery.consentmanager.net;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.consentmanager.net https://a.delivery.consentmanager.net https://www.googletagmanager.com https://identity.netlify.com;
      style-src 'self' 'unsafe-inline' https://cdn.consentmanager.net https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https: https://i.imgur.com https://imgur.com;
      font-src 'self' data: https: https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      connect-src 'self' https://a.delivery.consentmanager.net https://region1.analytics.google.com https://www.google-analytics.com;
      frame-src 'self' https://cdn.consentmanager.net;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Forms configuration
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Netlify Functions (if needed in the future)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/styles.css"
  to = "/styles/styles.css"
  status = 200

[[redirects]]
  from = "/dropdown.css"
  to = "/styles/dropdown.css"
  status = 200 